package io.gitplag.core.rest

val nameMap = mapOf(
    "alexkat20" to "student_1",
    "GrafEnters" to "student_2",
    "marycia624" to "student_3",
    "DamirJann" to "student_4",
    "TheTh1rt33nth" to "student_5",
    "DimaKurd" to "student_6",
    "Neoplayer" to "student_7",
    "mpu20" to "student_8",
    "amandany" to "student_9",
    "YanTszyafen" to "student_10",
    "xe-esina" to "student_11",
    "aumetov7" to "student_12",
    "AT4-CGSG" to "student_13",
    "Anastasia717" to "student_14",
    "ogalay" to "student_15",
    "InD1ggo" to "student_16",
    "MorozSerge" to "student_17",
    "gezimur" to "student_18",
    "ilyaryabikin" to "student_19",
    "anyasamoylova" to "student_20",
    "ekaterinadidenko20" to "student_21",
    "Grennwolf" to "student_22",
    "VrezhAleksDev" to "student_23",
    "Vikatimoshenko3103" to "student_24",
    "DanilPushkarev" to "student_25",
    "usennon" to "student_26",
    "belonel" to "student_27",
    "Sphenodon" to "student_28",
    "Budurgus" to "student_29",
    "Streaxz" to "student_30",
    "asvarish" to "student_31",
    "PinkDrifter" to "student_32",
    "valeria0309" to "student_33",
    "root5427" to "student_34",
    "CoffeeTime66" to "student_35"
)