package io.gitplag.core.rest

val nameMap = mapOf(
    "aumetov7" to "student1",
    "Budurgus" to "student2",
    "Sphenodon" to "student3",
    "belonel" to "student4",
    "usennon" to "student5",
    "Vikatimoshenko3103" to "student6",
    "VrezhAleksDev" to "student7",
    "DanilPushkarev" to "student8",
    "ekaterinadidenko20" to "student9",
    "Grennwolf" to "student10",
    "anyasamoylova" to "student11",
    "ilyaryabikin" to "student12",
    "MorozSerge" to "student13",
    "gezimur" to "student14",
    "InD1ggo" to "student15",
    "valeria0309" to "student16",
    "ogalay" to "student17",
    "Anastasia717" to "student18",
    "xe-esina" to "student19",
    "YanTszyafen" to "student20",
    "amandany" to "student21",
    "mpu20" to "student22",
    "alexkat20" to "student23",
    "GrafEnters" to "student24",
    "marycia624" to "student25",
    "DamirJann" to "student26",
    "TheTh1rt33nth" to "student27",
    "AT4-CGSG" to "student28",
    "DimaKurd" to "student29",
    "Neoplayer" to "student30",
    "Streaxz" to "student31",
    "PinkDrifter" to "student32",
    "root5427" to "student33",
    "CoffeeTime66" to "student34"
)