package io.gitplag.analysis

import io.gitplag.model.data.AnalysisSettings
import io.gitplag.model.entity.Analysis

/**
 * Main analysis class
 */
interface AnalysisRunner {

    /**
     * Run analysis with [settings]
     */
    fun run(settings: AnalysisSettings): Analysis

    /**
     * Run all analyzes with [settingsList]
     */
    fun run(settingsList: List<AnalysisSettings>): List<Analysis>

}

fun main() {
    val of = setOf(
        "alexkat20",
        "alexkat20",
        "GrafEnters",
        "GrafEnters",
        "marycia624",
        "marycia624",
        "DamirJann",
        "DamirJann",
        "TheTh1rt33nth",
        "TheTh1rt33nth",
        "TheTh1rt33nth",
        "DimaKurd",
        "DimaKurd",
        "Neoplayer",
        "Neoplayer",
        "mpu20",
        "mpu20",
        "amandany",
        "amandany",
        "YanTszyafen",
        "YanTszyafen",
        "xe-esina",
        "xe-esina",
        "aumetov7",
        "aumetov7",
        "AT4-CGSG",
        "AT4-CGSG",
        "Anastasia717",
        "Anastasia717",
        "ogalay",
        "ogalay",
        "InD1ggo",
        "InD1ggo",
        "MorozSerge",
        "MorozSerge",
        "gezimur",
        "gezimur",
        "ilyaryabikin",
        "ilyaryabikin",
        "anyasamoylova",
        "anyasamoylova",
        "ekaterinadidenko20",
        "ekaterinadidenko20",
        "Grennwolf",
        "Grennwolf",
        "VrezhAleksDev",
        "VrezhAleksDev",
        "Vikatimoshenko3103",
        "Vikatimoshenko3103",
        "DanilPushkarev",
        "DanilPushkarev",
        "usennon",
        "usennon",
        "belonel",
        "belonel",
        "Sphenodon",
        "Sphenodon",
        "Budurgus",
        "Budurgus",
        "aumetov7",
        "aumetov7",
        "Streaxz",
        "Streaxz",
        "asvarish",
        "asvarish",
        "PinkDrifter",
        "PinkDrifter",
        "aumetov7",
        "aumetov7",
        "TheTh1rt33nth",
        "TheTh1rt33nth",
        "TheTh1rt33nth",
        "Budurgus",
        "Budurgus",
        "xe-esina",
        "xe-esina",
        "Sphenodon",
        "Sphenodon",
        "marycia624",
        "marycia624",
        "Grennwolf",
        "Grennwolf",
        "DanilPushkarev",
        "DanilPushkarev",
        "anyasamoylova",
        "anyasamoylova",
        "GrafEnters",
        "GrafEnters",
        "YanTszyafen",
        "YanTszyafen",
        "MorozSerge",
        "MorozSerge",
        "mpu20",
        "mpu20",
        "InD1ggo",
        "InD1ggo",
        "ogalay",
        "ogalay",
        "gezimur",
        "gezimur",
        "alexkat20",
        "alexkat20",
        "DamirJann",
        "DamirJann",
        "DimaKurd",
        "DimaKurd",
        "DimaKurd",
        "DimaKurd",
        "Neoplayer",
        "Neoplayer",
        "ilyaryabikin",
        "ilyaryabikin",
        "amandany",
        "amandany",
        "AT4-CGSG",
        "AT4-CGSG",
        "VrezhAleksDev",
        "VrezhAleksDev",
        "Vikatimoshenko3103",
        "Vikatimoshenko3103",
        "belonel",
        "belonel",
        "ekaterinadidenko20",
        "ekaterinadidenko20",
        "usennon",
        "usennon",
        "aumetov7",
        "aumetov7",
        "Streaxz",
        "Streaxz",
        "asvarish",
        "asvarish",
        "Anastasia717",
        "Anastasia717",
        "PinkDrifter",
        "PinkDrifter",
        "TheTh1rt33nth",
        "Grennwolf",
        "Anastasia717",
        "valeria0309",
        "GrafEnters",
        "DanilPushkarev",
        "Budurgus",
        "InD1ggo",
        "Streaxz",
        "marycia624",
        "gezimur",
        "mpu20",
        "PinkDrifter",
        "usennon",
        "Sphenodon",
        "MorozSerge",
        "root5427",
        "CoffeeTime66",
        "Vikatimoshenko3103",
        "ilyaryabikin",
        "ilyaryabikin",
        "YanTszyafen",
        "Neoplayer",
        "ekaterinadidenko20",
        "anyasamoylova",
        "DimaKurd",
        "alexkat20",
        "ogalay",
        "VrezhAleksDev",
        "amandany",
        "AT4-CGSG",
        "xe-esina",
        "belonel",
        "asvarish",
        "AT4-CGSG",
        "aumetov7"
    )

    var i = 1
    for (student in of) {
        println("\"$student\" to \"student_${i++}\",")
    }

    mapOf(
        "alexkat20" to "student_1",
        "GrafEnters" to "student_2",
        "marycia624" to "student_3",
        "DamirJann" to "student_4",
        "TheTh1rt33nth" to "student_5",
        "DimaKurd" to "student_6",
        "Neoplayer" to "student_7",
        "mpu20" to "student_8",
        "amandany" to "student_9",
        "YanTszyafen" to "student_10",
        "xe-esina" to "student_11",
        "aumetov7" to "student_12",
        "AT4-CGSG" to "student_13",
        "Anastasia717" to "student_14",
        "ogalay" to "student_15",
        "InD1ggo" to "student_16",
        "MorozSerge" to "student_17",
        "gezimur" to "student_18",
        "ilyaryabikin" to "student_19",
        "anyasamoylova" to "student_20",
        "ekaterinadidenko20" to "student_21",
        "Grennwolf" to "student_22",
        "VrezhAleksDev" to "student_23",
        "Vikatimoshenko3103" to "student_24",
        "DanilPushkarev" to "student_25",
        "usennon" to "student_26",
        "belonel" to "student_27",
        "Sphenodon" to "student_28",
        "Budurgus" to "student_29",
        "Streaxz" to "student_30",
        "asvarish" to "student_31",
        "PinkDrifter" to "student_32",
        "valeria0309" to "student_33",
        "root5427" to "student_34",
        "CoffeeTime66" to "student_35"
    )

}